### ISSUE TITLE
replace it with endswith()

### ISSUE THREAD

**Issue by Endlex-net** [TesterCC/Python3Scripts#1]
https://github.com/TesterCC/Python3Scripts/blob/fba7094cc8fc5510065a080c581dfd092ac94cec/suanfatujie/graph_demo.py#L34

replace it with endswith()
测试一波 github的功能

**Comment by TesterCC** [comment]
> [Python3Scripts/suanfatujie/graph_demo.py](https://github.com/TesterCC/Python3Scripts/blob/fba7094cc8fc5510065a080c581dfd092ac94cec/suanfatujie/graph_demo.py#L34)
> 
> Line 34 in [fba7094](/TesterCC/Python3Scripts/commit/fba7094cc8fc5510065a080c581dfd092ac94cec)
> 
>  return name[-1] == 'm'   # Python2可以，Python3报错 
> replace it with endswith()
> 测试一波 github的功能

Thanks for your advice, it's OK.
